package com.reliaquest.api.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents an Employee entity in the system.
 * This class is used for both receiving data from the mock employee API
 * and returning employee data to API consumers.
 *
 * <p>The JSON property names use snake_case to match the mock server's API contract.
 * For example, the Java field 'employeeName' maps to 'employee_name' in JSON.</p>
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Employee {

    /**
     * Unique identifier for the employee.
     * Generated by the mock server as a UUID string.
     */
    private String id;

    /**
     * Full name of the employee.
     * Maps to 'employee_name' in JSON responses.
     */
    @JsonProperty("employee_name")
    private String employeeName;

    /**
     * Annual salary of the employee in the system's base currency.
     * Maps to 'employee_salary' in JSON responses.
     * Must be greater than zero when creating an employee.
     */
    @JsonProperty("employee_salary")
    private Integer employeeSalary;

    /**
     * Age of the employee in years.
     * Maps to 'employee_age' in JSON responses.
     * Valid range is 16-75 years as per business rules.
     */
    @JsonProperty("employee_age")
    private Integer employeeAge;

    /**
     * Job title or position of the employee.
     * Maps to 'employee_title' in JSON responses.
     */
    @JsonProperty("employee_title")
    private String employeeTitle;

    /**
     * Email address of the employee.
     * Maps to 'employee_email' in JSON responses.
     * Generated automatically by the mock server when creating an employee.
     */
    @JsonProperty("employee_email")
    private String employeeEmail;
}

